### ISSUE TITLE
TypeError: input.on is not a function

### ISSUE THREAD

**Issue by junca8** [jontewks/puppeteer-heroku-buildpack#11]
After following the directions, I'm seeing this error when puppeteer launches on heroku with the arguments mentioned and after installing the heroku puppeteer dependencies. Below is more of the error. Any ideas?

TypeError: input.on is not a function
2018-01-19T06:40:02.261833+00:00 app[web.1]:     at new Interface (readline.js:181:11)
2018-01-19T06:40:02.261834+00:00 app[web.1]:     at Object.createInterface (readline.js:64:10)
2018-01-19T06:40:02.261836+00:00 app[web.1]:     at Promise (/app/node_modules/puppeteer/lib/Launcher.js:196:25)
2018-01-19T06:40:02.261837+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-01-19T06:40:02.261840+00:00 app[web.1]:     at <anonymous>
2018-01-19T06:40:02.261837+00:00 app[web.1]:     at waitForWSEndpoint (/app/node_modules/puppeteer/lib/Launcher.js:195:10)
2018-01-19T06:40:02.261838+00:00 app[web.1]:     at Function.launch (/app/node_modules/puppeteer/lib/Launcher.js:133:39)
2018-01-19T06:40:02.944892+00:00 heroku[web.1]: Process exited with status 1
2018-01-19T06:40:02.807397+00:00 app[web.1]: events.js:183
2018-01-19T06:40:02.807407+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2018-01-19T06:40:02.807408+00:00 app[web.1]:       ^
2018-01-19T06:40:02.807409+00:00 app[web.1]: 
2018-01-19T06:40:02.807411+00:00 app[web.1]: Error: spawn /app/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome EAGAIN
2018-01-19T06:40:02.807412+00:00 app[web.1]:     at _errnoException (util.js:1024:11)
2018-01-19T06:40:02.807415+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
2018-01-19T06:40:02.807416+00:00 app[web.1]:     at onErrorNT (internal/child_process.js:372:16)
2018-01-19T06:40:02.807417+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-01-19T06:40:02.807418+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:180:9)
2018-01-19T06:40:02.831841+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-01-19T06:40:02.832193+00:00 app[web.1]: npm ERR! errno 1
2018-01-19T06:40:02.837169+00:00 app[web.1]: npm ERR! personal_project@2.0.0 start: `node server.js`
2018-01-19T06:40:02.837300+00:00 app[web.1]: npm ERR! Exit status 1
2018-01-19T06:40:02.837508+00:00 app[web.1]: npm ERR! 
2018-01-19T06:40:02.837647+00:00 app[web.1]: npm ERR! Failed at the personal_project@2.0.0 start script.
2018-01-19T06:40:02.837778+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-01-19T06:40:02.852375+00:00 app[web.1]: 
2018-01-19T06:40:02.852951+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2018-01-19T06:40:02.853286+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-01-19T06_40_02_839Z-debug.log
2018-01-19T06:40:02.961374+00:00 heroku[web.1]: State changed from up to crashed
2018-01-19T06:40:02.964058+00:00 heroku[web.1]: State changed from crashed to starting
2018-01-19T06:40:11.479178+00:00 heroku[web.1]: Starting process with command `npm start`

**Comment by jontewks** [comment]
Haven't seen anything like this before. Do you happen to have this project on your github? I'd like to check out the code running if thats possible.

**Comment by junca8** [comment]
Do you have gitlab? I'm more than happy to temporarily add you to the project so you can check it out.

**Comment by jontewks** [comment]
Sorry I don't have gitlab. Would be nice to see if we can figure it out here though just in case anyone else comes looking for the answer. Can you also post your heroku buildpacks? Some people have reported that switching their order has helped, might be worth a shot too?

**Comment by jontewks** [comment]
Haven't heard back. Feel free to reopen if the issue persists.

**Comment by KengoTODA** [comment]
Yesterday I faced this problem on Heroku. I use puppeteer v1.12.2 and node.js v10.15.1.
Not sure how to reproduce for now... maybe when failed to launch Chrome?

```
TypeError: input.on is not a function
  File "readline.js", line 189, col 11, in new Interface
  File "readline.js", line 69, col 10, in Object.createInterface
  File "/app/node_modules/puppeteer/lib/Launcher.js", line 345, col 25, in Promise
    const rl = readline.createInterface({ input: chromeProcess.stderr });
  ?, in new Promise
  File "/app/node_modules/puppeteer/lib/Launcher.js", line 344, col 10, in waitForWSEndpoint
    return new Promise((resolve, reject) => {
  File "/app/node_modules/puppeteer/lib/Launcher.js", line 169, col 41, in Launcher.launch
    const browserWSEndpoint = await waitForWSEndpoint(chromeProcess, timeout, this._preferredRevision);
```

You may visit [my sentry log](https://sentry.io/share/issue/57dc9ca8a0494776ad5b326357a72279/) for reference.

**Comment by jontewks** [comment]
@KengoTODA are you saying you hit this error once and then aren't able to reproduce it any longer?

**Comment by KengoTODA** [comment]
Yes.

**Comment by jontewks** [comment]
@KengoTODA gonna be hard to say for sure what the cause was if we can't repro it and then try things to resolve it. There are a couple other issues that had something similar but never got a for sure answer on what the cause was. My best guess was having `headless: true` since that breaks in heroku. If it comes back up you can feel free to open another issue, but the buildpack is for getting puppeteer running on heroku and so it is likely something unrelated to the buildpack specifically. Hope it doesn't show up any more for you!

**Comment by KengoTODA** [comment]
Thanks for your help! For now I have no problem. I will create different issue when I need.

BTW I cannot get your point at:

> My best guess was having `headless: true`

Do you mean that it's better to avoid using `headless: true`? It is [default configuration](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions), so do I need to configure `headless: false` explicitly?

**Comment by jontewks** [comment]
Hah whoops my mistake. I meant headless: false, as heroku has no way to display it in a non headless state leading to issues.

**Comment by KengoTODA** [comment]
Oh, I see. [My code uses the default config](https://github.com/KengoTODA/rtd-bot/blob/46c42cdfee75437d58974a92fac7e80f6faf5dd5/src/rtd.ts#L55-L57), then it should have no problem. Thank you.

**Comment by drogerie21** [comment]
I get the same error when bundling puppeteer-core and node-chromium with webpack:
```
TypeError: input.on is not a function
    at new Interface (readline.js:207:11)
    at Object.createInterface (readline.js:75:10)
```
This is reproducable!

**Comment by chrisdel101** [comment]
I have this error to. I also get `Error: spawn /app/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome EAGAIN`. I've yet to find a solution. Has anyone found one?

**Comment by benjii** [comment]
I am getting this as well:

```
TypeError: input.on is not a function
    at new Interface (readline.js:181:11)
    at Object.createInterface (readline.js:64:10)
    at packages/bustle:workers/server/retrieve-nutrans-work-order-worker.js:145:43
    at Object.cb (/opt/meteor/dist/bundle/programs/server/npm/node_modules/ftp/lib/connection.js:606:15)
    at Parser.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/ftp/lib/connection.js:113:22)
    at emitTwo (events.js:126:13)
    at Parser.emit (events.js:214:7)
    at Parser._write (/opt/meteor/dist/bundle/programs/server/npm/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Parser.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (/opt/meteor/dist/bundle/programs/server/npm/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
```

This is in MeteorJS and within a worker. This error also kills the node that it is running on (we use Docker Swarm).

**Comment by therightstuff** [comment]
This is still happening, running a standalone .js file using the sample code from the documentation:

```
readline.js:214
    input.on('data', ondata);
          ^

TypeError: input.on is not a function
    at new Interface (readline.js:214:11)
    at Object.createInterface (readline.js:78:10)
    at Object.<anonymous> (/Users/me/myscript.js:16:21)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by therightstuff** [comment]
> This is still happening, running a standalone .js file using the sample code from the documentation:
> 
> ```
> readline.js:214
>     input.on('data', ondata);
>           ^
> 
> TypeError: input.on is not a function
>     at new Interface (readline.js:214:11)
>     at Object.createInterface (readline.js:78:10)
>     at Object.<anonymous> (/Users/me/myscript.js:16:21)
>     at Module._compile (internal/modules/cjs/loader.js:955:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
>     at Module.load (internal/modules/cjs/loader.js:811:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
>     at internal/main/run_main_module.js:17:11
> ```

Right, easy resolution: the sample code wasn't alone and I subsequently realized that I was also using the `child_process` module which I had included with the oddly-standard `let process = require('child_process');`. As soon as I changed it to something else `readline` worked, obviously assigning anything to `process` is an invitation for trouble.

**Comment by cakemountain** [comment]
@jontewks any updates here? I'm getting this error trying to use puppeteer on Heroku with both this buildpack and [the fork that contains the different international font sets](https://github.com/CoffeeAndCode/puppeteer-heroku-buildpack).

**Comment by jontewks** [comment]
@cakemountain hey, no no updates from me. This buildpack is only to get puppeteer running on heroku. All it does is get the necessary packages downloaded and available for chromium to run correctly. So I don't believe an issue that arises after chromium is running would be due to this buildpack.

**Comment by cakemountain** [comment]
@jontewks I ended up figuring out the issue: it was because our 2X dyno was running out of memory. We had to upgrade to a performance-M dyno in order to prevent puppeteer from crashing the application.

As far as the scope of this issue is concerned I believe the error cited in the description is the result of Chromium crashing, from memory consumption or otherwise. Just wanted to followup for posterity.

One unrelated problem we noticed was that adding this buildpack added about 100M to the slug size which was a separate issue we had to deal with. Not sure if there's any package bloat that could be cleaned up, just thought I'd put it on your radar. Apart from that this buildpack has been awesome.

**Comment by jontewks** [comment]
@cakemountain thanks a lot for that extra info!

Yeah the package size does suck. I don't fully understand how it works on heroku's end, but even after clearing all the cache I could find, my slug size was stuck at an amount larger than the max allowed, but starting a new project with the same code resulted in a lower slug size. Thought I'd also mention that here just in case someone runs into that in the future.

As far as the package bloat goes, I think there are some here that aren't necessary as this was written to allow some of the other deprecated heroku stacks to run as well. Perhaps making some new versions only work with the newer stacks would be a help.
