### ISSUE TITLE
Error: read ENOTCONN

### ISSUE THREAD

**Issue by cakemountain** [jontewks/puppeteer-heroku-buildpack#112]
Hi @jontewks , I'm having issues with this buildpack on Heroku.

Things I've tried:
- making sure to include `args: ['--no-sandbox', '--disable-setuid-sandbox']` in the `puppeteer.launch` command
- use the default `headless: true` in the `puppeteer.launch` command
- clear the build cache, remove, then re-add the buildpack and redeploy

But no luck :( Looks like other people have experienced the same/similar error:
- https://stackoverflow.com/questions/67494667/same-question-as-one-asked-a-few-days-ago-why-is-this-puppeteer-code-not-workin
- https://stackoverflow.com/questions/64173252/pupeeteer-heroku-buildpack-exiting-the-lunch-statement-on-heroku

Versions:
- `"puppeteer": "^13.7.0"`
- `"node": "16.13.1"`
- `"npm": "8.1.2"`
- `"yarn": "1.22.5"`
- `"typescript": "^4.5.4"`

The error I'm getting looks like...

```
2022-08-27T19:59:43.518282+00:00 app[worker.1]: node:events:368
2022-08-27T19:59:43.518284+00:00 app[worker.1]: throw er; // Unhandled 'error' event
2022-08-27T19:59:43.518287+00:00 app[worker.1]: ^
2022-08-27T19:59:43.518288+00:00 app[worker.1]: 
2022-08-27T19:59:43.518289+00:00 app[worker.1]: Error: read ENOTCONN
2022-08-27T19:59:43.518289+00:00 app[worker.1]: at tryReadStart (node:net:592:20)
2022-08-27T19:59:43.518289+00:00 app[worker.1]: at Socket._read (node:net:603:5)
2022-08-27T19:59:43.518290+00:00 app[worker.1]: at Socket.Readable.read (node:internal/streams/readable:487:10)
2022-08-27T19:59:43.518291+00:00 app[worker.1]: at Socket.read (node:net:644:39)
2022-08-27T19:59:43.518291+00:00 app[worker.1]: at new Socket (node:net:401:12)
2022-08-27T19:59:43.518292+00:00 app[worker.1]: at Object.Socket (node:net:284:41)
2022-08-27T19:59:43.518292+00:00 app[worker.1]: at createSocket (node:internal/child_process:327:14)
2022-08-27T19:59:43.518293+00:00 app[worker.1]: at ChildProcess.spawn (node:internal/child_process:444:23)
2022-08-27T19:59:43.518293+00:00 app[worker.1]: at Object.spawn (node:child_process:698:9)
2022-08-27T19:59:43.518294+00:00 app[worker.1]: at BrowserRunner.start (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:95:34)
2022-08-27T19:59:43.518295+00:00 app[worker.1]: at ChromeLauncher.launch (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:113:16)
2022-08-27T19:59:43.518295+00:00 app[worker.1]: Emitted 'error' event on Interface instance at:
2022-08-27T19:59:43.518295+00:00 app[worker.1]: at Socket.onerror (node:readline:265:10)
2022-08-27T19:59:43.518296+00:00 app[worker.1]: at Socket.emit (node:events:390:28)
2022-08-27T19:59:43.518296+00:00 app[worker.1]: at Socket.emit (node:domain:475:12)
2022-08-27T19:59:43.518296+00:00 app[worker.1]: at emitErrorNT (node:internal/streams/destroy:157:8)
2022-08-27T19:59:43.518297+00:00 app[worker.1]: at emitErrorCloseNT (node:internal/streams/destroy:122:3)
2022-08-27T19:59:43.518297+00:00 app[worker.1]: at processTicksAndRejections (node:internal/process/task_queues:83:21) {
2022-08-27T19:59:43.518297+00:00 app[worker.1]: errno: -107,
2022-08-27T19:59:43.518298+00:00 app[worker.1]: code: 'ENOTCONN',
2022-08-27T19:59:43.518298+00:00 app[worker.1]: syscall: 'read'
2022-08-27T19:59:43.518298+00:00 app[worker.1]: }
2022-08-27T19:59:43.538852+00:00 app[worker.1]: error Command failed with exit code 1.
2022-08-27T19:59:43.538962+00:00 app[worker.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-08-27T19:59:43.561462+00:00 app[worker.1]: error Command failed.
2022-08-27T19:59:43.561490+00:00 app[worker.1]: Exit code: 1
2022-08-27T19:59:43.561492+00:00 app[worker.1]: Command: /app/.heroku/node/bin/node
2022-08-27T19:59:43.561493+00:00 app[worker.1]: Arguments: /app/.yarn/releases/yarn-1.22.5.cjs worker-start
2022-08-27T19:59:43.561493+00:00 app[worker.1]: Directory: /app/packages/processing
2022-08-27T19:59:43.561493+00:00 app[worker.1]: Output:
2022-08-27T19:59:43.561494+00:00 app[worker.1]: 
2022-08-27T19:59:43.561783+00:00 app[worker.1]: info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
2022-08-27T19:59:43.760317+00:00 heroku[worker.1]: Process exited with status 1
2022-08-27T19:59:43.831973+00:00 heroku[worker.1]: State changed from up to crashed
```

Any suggestions for this? It would be really nice to be able to use this to run puppeteer on Heroku. Thanks!

**Comment by cakemountain** [comment]
@jontewks I also should add, I tried:
- Upgrading to the latest Puppeteer version, 16.2.0
- Remove `'--disable-setuid-sandbox'` from the `args` on puppeteer.launch

Some additional important details about the errors I'm seeing:
- This error seems to only happen periodically -- the majority of pages seem to be crawled just fine
- This error causes the Heroku proc to crash and have to restart
- I can't seem to catch this error, even by try/catch-ing the entirety of the function all Puppeteer invocations happen in -- if this weren't the case, the error would be workable.


Here is my current code:

```
export const setupPuppeteer = async (): Promise<any> => {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  });

  const page = await browser.newPage();

  await page.setUserAgent(
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36'
  );

  await page.setViewport({ width: 1920, height: 1080 });

  await page.setDefaultNavigationTimeout(15000);
  await page.setDefaultTimeout(15000);
  
  return [page, browser];
}
```

Can you help me make this code more reliable?

**Comment by jontewks** [comment]
Hey @cakemountain 

I don't think I can help out in this scenario. This buildpack only adds libraries to Heroku's runtime to allow Chromium to function. As far as I'm aware it doesn't have an effect on how Chromium runs after its started. I think the Puppeteer repo itself would be a better place to get help with it's use. There are mentions of it with Puppeteer outside of Heroku as well, so I wouldn't think this was a Heroku specific thing: https://github.com/pedroslopez/whatsapp-web.js/issues/1133
