### ISSUE TITLE
Chromium revision error on Heroku

### ISSUE THREAD

**Issue by fabianhijlkema** [jontewks/puppeteer-heroku-buildpack#114]
I'm trying to set up a simple example project with Puppeteer on Heroku. But I keep getting an error.

```
 > headless-chrome@1.0.0 start
2022-10-24T08:27:15.091007+00:00 app[web.1]: > node app.js
2022-10-24T08:27:15.091007+00:00 app[web.1]: 
2022-10-24T08:27:15.418046+00:00 app[web.1]: App listening on port 49007
2022-10-24T08:27:15.467006+00:00 heroku[web.1]: State changed from starting to up
2022-10-24T08:27:34.619856+00:00 app[web.1]: Screenshotting: http://google.com
2022-10-24T08:27:34.637357+00:00 app[web.1]: /app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:120
2022-10-24T08:27:34.637361+00:00 app[web.1]: throw new Error(`Run \`npm install\` to download the correct Chromium revision (${this.puppeteer.browserRevision}).`);
2022-10-24T08:27:34.637362+00:00 app[web.1]: ^
2022-10-24T08:27:34.637362+00:00 app[web.1]: 
2022-10-24T08:27:34.637363+00:00 app[web.1]: Error: Run `npm install` to download the correct Chromium revision (1045629).
2022-10-24T08:27:34.637367+00:00 app[web.1]: at ChromeLauncher.resolveExecutablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:120:27)
2022-10-24T08:27:34.637367+00:00 app[web.1]: at ChromeLauncher.executablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:166:25)
2022-10-24T08:27:34.637367+00:00 app[web.1]: at ChromeLauncher.launch (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:70:37)
2022-10-24T08:27:34.637368+00:00 app[web.1]: at async /app/app.js:22:29
2022-10-24T08:27:34.643391+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/?url=google.com" host=test-fabian-puppeteer.herokuapp.com request_id=d8c33707-4ef0-4864-8f35-91535e5cd346 fwd="85.146.168.94" dyno=web.1 connect=0ms service=29ms status=503 bytes=0 protocol=https
2022-10-24T08:27:34.796339+00:00 heroku[web.1]: Process exited with status 1
2022-10-24T08:27:34.862515+00:00 heroku[web.1]: State changed from up to crashed
```

I followed the basic setup of this site, after trying to use the buildpack/Puppeteer in a larger project (which failed as well). Although I did do some updates on engine and packages compared to this example.
https://timleland.com/headless-chrome-on-heroku/

package.json
```
{
  "name": "headless-chrome",
  "engines": {
    "node": "16.x"
  },
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "dependencies": {
    "express": "^4.16.2",
    "puppeteer": "^19.1.0",
    "valid-url": "^1.0.9"
  },
  "scripts": {
    "start": "node app.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

Used buildpack + Node/Heroku build pack
```
https://github.com/jontewks/puppeteer-heroku-buildpack#22.0.0
```

I've also tried to clear the cache.

**Comment by fabianhijlkema** [comment]
Similar with the Firefox version btw. I'm guessing I'm missing something simple here.

```
2022-10-24T09:29:04.725565+00:00 app[web.1]: /app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:122
2022-10-24T09:29:04.725567+00:00 app[web.1]: throw new Error(`Run \`PUPPETEER_PRODUCT=firefox npm install\` to download a supported Firefox browser binary.`);
2022-10-24T09:29:04.725567+00:00 app[web.1]: ^
2022-10-24T09:29:04.725568+00:00 app[web.1]: 
2022-10-24T09:29:04.725569+00:00 app[web.1]: Error: Run `PUPPETEER_PRODUCT=firefox npm install` to download a supported Firefox browser binary.
2022-10-24T09:29:04.725570+00:00 app[web.1]: at FirefoxLauncher.resolveExecutablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:122:27)
2022-10-24T09:29:04.725571+00:00 app[web.1]: at FirefoxLauncher.executablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/FirefoxLauncher.js:144:21)
2022-10-24T09:29:04.725571+00:00 app[web.1]: at FirefoxLauncher.launch (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/FirefoxLauncher.js:74:38)
2022-10-24T09:29:04.725571+00:00 app[web.1]: at async /app/app.js:22:29
```

**Comment by jontewks** [comment]
Hey @fabianhijlkema can you please post the code you are running as well? Thanks.

**Comment by fabianhijlkema** [comment]
I did not really change anything based on the example from the provided URL. Worked locally. Also the version in the larger project worked locally, and on other platforms than Heroku.

```
const express = require('express');
const app = express();
const puppeteer = require('puppeteer');
const port = process.env.PORT || 8080;
const validUrl = require('valid-url');

var parseUrl = function(url) {
    url = decodeURIComponent(url)
    if (!/^(?:f|ht)tps?\:\/\//.test(url)) {
        url = 'http://' + url;
    }

    return url;
};

app.get('/', function(req, res) {
    var urlToScreenshot = parseUrl(req.query.url);

    if (validUrl.isWebUri(urlToScreenshot)) {
        console.log('Screenshotting: ' + urlToScreenshot);
        (async() => {
            const browser = await puppeteer.launch({
                args: ['--no-sandbox', '--disable-setuid-sandbox']
            });

            const page = await browser.newPage();
            await page.goto(urlToScreenshot);
            await page.screenshot().then(function(buffer) {
                res.setHeader('Content-Disposition', 'attachment;filename="' + urlToScreenshot + '.png"');
                res.setHeader('Content-Type', 'image/png');
                res.send(buffer)
            });

            await browser.close();
        })();
    } else {
        res.send('Invalid url: ' + urlToScreenshot);
    }

});

app.listen(port, function() {
    console.log('App listening on port ' + port)
})
```

**Comment by jontewks** [comment]
Thanks.

Looks like puppeteer recently changed the directory where they chromium install lives, so its really looking like a caching issue. Here is some talk about it: https://github.com/puppeteer/puppeteer/issues/9119

Can you try taking this exact code and putting it into a new Heroku app? I've fixed build size issues doing that before even when clearing the heroku cache didn't work.

I'm happy to keep helping out but this is an issue with Puppeteer and not the buildpack specifically since all the buildpack does is add libraries that chromium needs to run on Heroku.
