### ISSUE TITLE
Error: Could not find Chromium

### ISSUE THREAD

**Issue by arainey2022** [jontewks/puppeteer-heroku-buildpack#119]
Hi there, thank you for this buildpack — it's referred to everywhere online!

I'm facing an issue though with my app on Heroku.

The full error is:

```
Error: Could not find Chromium (rev. 1056772). This can occur if either
2022-11-10T06:44:07.938983+00:00 app[web.1]:  1. you did not perform an installation before running the script (e.g. `npm install`) or
2022-11-10T06:44:07.938983+00:00 app[web.1]:  2. your cache path is incorrectly configured (which is: /app/.cache/puppeteer).
2022-11-10T06:44:07.938983+00:00 app[web.1]: For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
2022-11-10T06:44:07.938984+00:00 app[web.1]:     at ChromeLauncher.resolveExecutablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:120:27)
2022-11-10T06:44:07.938984+00:00 app[web.1]:     at ChromeLauncher.executablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:166:25)
2022-11-10T06:44:07.938985+00:00 app[web.1]:     at PuppeteerNode.executablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/PuppeteerNode.js:162:105)
2022-11-10T06:44:07.938985+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:29:145)
2022-11-10T06:44:07.938985+00:00 app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1159:14)
2022-11-10T06:44:07.938986+00:00 app[web.1]:     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
2022-11-10T06:44:07.938986+00:00 app[web.1]:     at Module.load (node:internal/modules/cjs/loader:1037:32)
2022-11-10T06:44:07.938986+00:00 app[web.1]:     at Module._load (node:internal/modules/cjs/loader:878:12)
2022-11-10T06:44:07.938986+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
2022-11-10T06:44:07.938987+00:00 app[web.1]:     at node:internal/main/run_main_module:23:47
```

My code for index.js (only js file) is:

```
const puppeteer = require('puppeteer-extra')
const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
const { executablePath } = require('puppeteer')
const axios = require('axios')

//pupeteer plugins
puppeteer.use(
    RecaptchaPlugin({
        provider: {
            id: '2captcha',
            token: '7c9b4bc60947a5d0b207ccfccc03bf3c'
        },
        visualFeedback: true //colorize reCAPTCHAs (violet = detected, green = solved)
    })
)
puppeteer.use(StealthPlugin())

//pupeteer crawl
try {

    puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'], headless: true, executablePath: executablePath(), ignoreHTTPSErrors: true }).then(async browser => {

        console.log('Running tests..')
        const page = await browser.newPage()
        await page.goto('https://bot.sannysoft.com')
        await page.setViewport({ width: 1680, height: 857 })
        await page.waitForTimeout(5000)
        await page.screenshot({ path: 'testresult.png', fullPage: true })
        await browser.close()
        console.log(`All done, check the screenshot. ✨`)

    })
} catch (error) {
    console.error(error);
}
```

And these are my build packs in Heroku:

<img width="822" alt="Screenshot 2022-11-10 at 06 49 47" src="https://user-images.githubusercontent.com/117843155/201020384-4c13a0cd-0885-4848-87e7-71ea0d8b848e.png">

I've been battling with these for a few days and tried everything, have you seen this error before?

**Comment by jiten-cardeo** [comment]
I'm currently having a similar issue, but my underlying issue is that installing the buildpack AND letting puppeteer install chromium means my heroku slug > 500mb, which fails the build.

**Comment by alexpluto** [comment]
@jiten-cardeo Interesting. Sounds like you might me a step ahead of me at least.

Are you installing Chromium because you want to run headless:false on Heroku?

Will await the guru @jontewks to weigh in as well.

**Comment by jontewks** [comment]
Puppeteer v19 changed the location of where chromium is installed. If you clear your Heroku cache or revert to a puppeteer version before that change will resolve it. Instructions are here for clearing cache: https://github.com/jontewks/puppeteer-heroku-buildpack#caching

**Comment by jiten-cardeo** [comment]
@jontewks - my heroku slug size was 250mb prior to adding:

1. puppeteer heroku build pack
2. puppeteer npm package (with chromium installed)

This results in the slug size being < 500mb. I have already tried clearing the cache a couple of times. When I open up the dyno, I can see that:

.cache folder - 400mb
.apt folder - 600mb

Am I still having a cache issue?

**Comment by arainey2022** [comment]
@jontewks thanks for getting back to me on this.

I tried:

1. Changing puppeteer version to 18.2.1, cleared cache, pushed to Heroku and got a new error:

```
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299
2022-11-11T12:15:35.530831+00:00 app[web.1]:             reject(new Error([
2022-11-11T12:15:35.530831+00:00 app[web.1]:                    ^
2022-11-11T12:15:35.530832+00:00 app[web.1]: 
2022-11-11T12:15:35.530832+00:00 app[web.1]: Error: Failed to launch the browser process!
2022-11-11T12:15:35.530833+00:00 app[web.1]: [21:21:1111/121535.515200:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
2022-11-11T12:15:35.530833+00:00 app[web.1]: [21:21:1111/121535.515254:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
2022-11-11T12:15:35.530833+00:00 app[web.1]: 
2022-11-11T12:15:35.530833+00:00 app[web.1]: 
2022-11-11T12:15:35.530833+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
2022-11-11T12:15:35.530833+00:00 app[web.1]: 
2022-11-11T12:15:35.530853+00:00 app[web.1]:     at onClose (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
2022-11-11T12:15:35.530853+00:00 app[web.1]:     at ChildProcess.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:290:24)
2022-11-11T12:15:35.530853+00:00 app[web.1]:     at ChildProcess.emit (node:events:525:35)
2022-11-11T12:15:35.530853+00:00 app[web.1]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

2. And then tried with Puppeteer v19.2.2, , cleared cache, pushed to Heroku and got the same error as my original comment.

Any more ideas? Thank you in advance.

**Comment by jontewks** [comment]
Are you still running in headless mode? It shouldn't be looking for a display.

I google searched that error and found lots of talk about it on the puppeteer repo and elsewhere if you need to research it further.

**Comment by arainey2022** [comment]
Thanks @jontewks, I'll keep looking.

Now exploring deploying this in a docker container on Heroku.

**Comment by MCKLtech** [comment]
I've also hit this error, I'm using it with Laravel:

`Exit Code: 1(General error)

Working directory: /app/public

Output:
================


Error Output:
================
Error: Could not find Chromium (rev. 1056772). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /app/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:120:27)
    at ChromeLauncher.executablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:166:25)
    at ChromeLauncher.launch (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:70:37)
    at async callChrome (/app/vendor/spatie/browsershot/bin/browser.js:84:23)`

**Comment by davidcalhoun** [comment]
Downgrading to Puppeteer 19 also worked here for a different setup running into a similar problem.  Created a ticket here for reference: https://github.com/puppeteer/puppeteer/issues/9304

**Comment by Wit3** [comment]
> Puppeteer v19 changed the location of where chromium is installed. If you clear your Heroku cache or revert to a puppeteer version before that change that will resolve it. Instructions are here for clearing cache: https://github.com/jontewks/puppeteer-heroku-buildpack#caching

clear cache doesn't resolve issue if i would use puppeteer v19
any solution?

**Comment by MCKLtech** [comment]
@Wit3 , see my comment above, it solved it for me. However I stopped using it as the performance was terrible versus 19 running locally.

**Comment by davidcalhoun** [comment]
When upgrading from Puppeteer 15 to 19 I ran into the same issue with Yarn - turns out I had to clear the entire `.yarn` directory which fixed it.  More details: https://github.com/puppeteer/puppeteer/issues/9304

**Comment by Wit3** [comment]
> @Wit3 , see my comment above, it solved it for me. However I stopped using it as the performance was terrible versus 19 running locally.

Yep, now i use 17.1.3



> When upgrading from Puppeteer 15 to 19 I ran into the same issue with Yarn - turns out I had to clear the entire `.yarn` directory which fixed it. More details: [puppeteer/puppeteer#9304](https://github.com/puppeteer/puppeteer/issues/9304)

with npm if i try to remove entire npm_modules folder and re-run `npm install` nothing change, issue is still present

**Comment by jungalwala** [comment]
I have been able to solve the problem installing puppeteer v19.7.2 in Heroku by adding the following file to be base directory of my project: "**.puppeteerrc.cjs**"

```
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};

```

Puppeteer v19 moved the cache directory and what this file does is tell the npm installer to move the cache directory from $HOME/.cache/puppeteer to the `current-working-directory/.cache/puppeteer`.  This file is also read by puppeteer when launched so it knows where to find the cached files.   I have tested this on Heroku22 and worked perfect.  Remember to add **.cache** to your .gitignore.

**Comment by arpitgoyall** [comment]
I found many solution but this worded for may and maybe helpful for others 😊

Add buildpack https://github.com/heroku/heroku-buildpack-google-chrome.git

Add executablePath in launch options for production only, you have to require puppeteer from modules

`const puppeteer = require("puppeteer");
{
...otherOptions,
executablePath: process.env.NODE_ENV === "production" ? process.env.PUPPETEER_EXECUTABLE_PATH : puppeteer.executablePath(),
}`

In heroku add env 
PUPPETEER_EXECUTABLE_PATH=/app/.apt/usr/bin/google-chrome
NODE_ENV = production

By doing this you are pointing your own chromium  instance 👍
