### ISSUE TITLE
Issue with build pack on particular revision of Chrome.

### ISSUE THREAD

**Issue by peterbrowse** [jontewks/puppeteer-heroku-buildpack#126]
I've gone through and tried to debug this as much as I can, I even tried switching to Firefox, but Heroku is still not playing ball with Puppeteer.

I've followed the instructions and tried clearing the cache, but no matter what I try, I'm getting this console error:

`2023-04-12T04:21:09.843468+00:00 app[web.1]: [4/12/2023, 4:21:09 AM][CRAWLER][ERROR] Error: Could not find Chromium (rev. 1108766). This can occur if either
2023-04-12T04:21:09.843481+00:00 app[web.1]:  1. you did not perform an installation before running the script (e.g. `npm install`) or
2023-04-12T04:21:09.843481+00:00 app[web.1]:  2. your cache path is incorrectly configured (which is: /app/.cache/puppeteer).
2023-04-12T04:21:09.843481+00:00 app[web.1]: For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
2023-04-12T04:21:09.843482+00:00 app[web.1]:     at ChromeLauncher.resolveExecutablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:289:27)
2023-04-12T04:21:09.843482+00:00 app[web.1]:     at ChromeLauncher.executablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:163:25)
2023-04-12T04:21:09.843483+00:00 app[web.1]:     at ChromeLauncher.computeLaunchArguments (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:80:37)
2023-04-12T04:21:09.843483+00:00 app[web.1]:     at async ChromeLauncher.launch (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:83:28)
2023-04-12T04:21:09.843483+00:00 app[web.1]:     at async Crawler.scrapeAndCompare (/app/services/crawler.services.js:269:27)`

I've got the following argument flags on puppeteer.launch:

`browser = await puppeteer.launch({
                        args: [
                          '--no-sandbox',
                          '--disable-setuid-sandbox',
                        ]
                    });`

Any thoughts?

**Comment by jontewks** [comment]
Puppeteer recently changed the cache directory, so you can downgrade to v18 I think was the one before the change, or you can try it out with a new heroku app which sometimes helps with build issues I've had in the past, or you can try out the info from this blog post someone wrote about running into the same issue: https://nairihar.medium.com/how-to-use-puppeteer-in-heroku-9de2ab31bc11.

Let me know which you choose and what happens!

**Comment by jontewks** [comment]
I haven't tried it yet, but it also looks like you can add a puppeteer rc file to overwrite the directory of where the executable is downloaded, perhaps you can just set that to be the same path as in the above blog post and won't need to move files in bash?

https://pptr.dev/#configuration

**Comment by peterbrowse** [comment]
Thanks for getting back to me.
After spending a fair amount of time last night after submitting this "issue", I came to the same conclusion.

I'm specifying an rc file:

`const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};`

In an attempt to rectify exactly this. However, it's ignoring it. Classic.

Even after clearing build caches.

I will try the bash route before finally just downgrading to the last of version 18.

**Comment by peterbrowse** [comment]
I can confirm that the method you mentioned in the blog post works with version 19.8.5 of Puppeteer on heroku.

[https://nairihar.medium.com/how-to-use-puppeteer-in-heroku-9de2ab31bc11](url)
