### ISSUE TITLE
issue deploying to heroku

### ISSUE THREAD

**Issue by kevindurley** [jontewks/puppeteer-heroku-buildpack#134]
no issues until today, we have been using the build pack for ages but trying to deploy and this happens ..

can you please help? we have an urgent fix we need to deploy ... and we can't

thanks

Kevin

kevin@durley.net is my personal account
we are actually using the build pack on totalactivehub.com - i'm also kevin@totalactivehub.com

remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 20.x...
remote:        Downloading and installing node 20.11.1...
remote:        Using default npm version: 10.2.4
remote:
remote: -----> Installing dependencies
remote:        Installing node modules
remote:        npm notice
remote:        npm notice New minor version of npm available! 10.2.4 -> 10.4.0
remote:        npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
remote:        npm notice Run `npm install -g npm@10.4.0` to update!
remote:        npm notice
remote:        npm ERR! code 1
remote:        npm ERR! path /tmp/build_1706973a/node_modules/puppeteer
remote:        npm ERR! command failed
remote:        npm ERR! command sh -c node install.js
remote:        npm ERR! ERROR: Failed to set up Chrome r115.0.5790.102! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
remote:        npm ERR! Error: Download failed: server returned code 500. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/linux64/chrome-linux64.zip
remote:        npm ERR!     at /tmp/build_1706973a/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:102:31
remote:        npm ERR!     at ClientRequest.requestCallback (/tmp/build_1706973a/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:79:13)
remote:        npm ERR!     at Object.onceWrapper (node:events:633:26)
remote:        npm ERR!     at ClientRequest.emit (node:events:518:28)
remote:        npm ERR!     at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
remote:        npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
remote:        npm ERR!     at TLSSocket.socketOnData (node:_http_client:535:22)
remote:        npm ERR!     at TLSSocket.emit (node:events:518:28)
remote:        npm ERR!     at addChunk (node:internal/streams/readable:559:12)
remote:        npm ERR!     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
remote:
remote:        npm ERR! A complete log of this run can be found in: /tmp/npmcache.7SBh1/_logs/2024-02-22T16_43_20_176Z-debug-0.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - Node version not specified in package.json
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:

**Comment by GLOBBYboi** [comment]
I got this issue today as well! I have no idea what happened! Please tell me if you figure out a solution for this! I need help with this as soon as possible.

**Comment by kevindurley** [comment]
@jontewks ... it seems like the issue is totally related to the fact that the build pack is downloading from here ...
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/linux64/chrome-linux64.zip
... which is returning an error 500

we currently cannot deploy :(

please help!

**Comment by GLOBBYboi** [comment]
@kevindurley Do you think that this issue will resolve itself soon? Or will we have to start using the puppeteer-chromium-resolver npm module for our Puppeteer apps on Heroku?

**Comment by kevindurley** [comment]
@GLOBBYboi - i REALLY hope it is resolved soon!
I have also raised a ticket on the Heroku website.

**Comment by jontewks** [comment]
Hey y’all. I also hope this is resolved soon for you but it doesn’t have anything to do with this build pack. This build pack installs packages used by puppeteer in production to run correctly, but doesn’t install puppeteer itself, which is where the issue lies. 

A 500 is an internal server error, so sounds like the download server is having an issue there. 

I believe an option you have is to skip the download as mentioned in the error logs and bundle your own version of chrome there for puppeteer to use, but that’s not something I have experience with.

**Comment by jontewks** [comment]
https://github.com/puppeteer/puppeteer/issues/11987

**Comment by kevindurley** [comment]
thanks @jontewks for the link and I understand it's not an issue with the buildpack ...
... and we need to 'wait' :/
i've tried setting the environment variable PUPPETEER_DOWNLOAD_BASE_URL="https://storage.googleapis.com/chrome-for-testing-public/" in heroku ... but it makes no difference.
Am I missing something?
Many thanks!

**Comment by kevindurley** [comment]
@GLOBBYboi ... just tried deploying again and it's working !! please retry

**Comment by GLOBBYboi** [comment]
@kevindurley Really?! I'll try it again!
