### ISSUE TITLE
Chrome can't start on Heroku

### ISSUE THREAD

**Issue by mataspetrikas** [jontewks/puppeteer-heroku-buildpack#19]
It seems that some of the libraries required by Chromium are missing:

```
2018-09-06T12:54:39.394402+00:00 app[web.1]: /app/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libpangoft2-1.0.so.0: cannot open shared object file: No such file or directory
2018-09-06T12:54:39.394405+00:00 app[web.1]: 
2018-09-06T12:54:39.394407+00:00 app[web.1]: 
2018-09-06T12:54:39.394409+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
2018-09-06T12:54:39.394411+00:00 app[web.1]: 
2018-09-06T12:54:39.394413+00:00 app[web.1]:     at onClose (/app/node_modules/puppeteer/lib/Launcher.js:299:14)
2018-09-06T12:54:39.394414+00:00 app[web.1]:     at Interface.helper.addEventListener (/app/node_modules/puppeteer/lib/Launcher.js:288:50)
2018-09-06T12:54:39.394417+00:00 app[web.1]:     at emitNone (events.js:111:20)
2018-09-06T12:54:39.394418+00:00 app[web.1]:     at Interface.emit (events.js:208:7)
2018-09-06T12:54:39.394420+00:00 app[web.1]:     at Interface.close (readline.js:368:8)
2018-09-06T12:54:39.394421+00:00 app[web.1]:     at Socket.onend (readline.js:147:10)
2018-09-06T12:54:39.394423+00:00 app[web.1]:     at emitNone (events.js:111:20)
2018-09-06T12:54:39.394424+00:00 app[web.1]:     at Socket.emit (events.js:208:7)
2018-09-06T12:54:39.394427+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1064:12)
2018-09-06T12:54:39.394429+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-09-06T12:54:39.395639+00:00 app[web.1]: (node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2018-09-06T12:54:39.395798+00:00 app[web.1]: (node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I tried ading the libpangoft2, but later it complained about other libs missing. Did the library list get updated in teh recent releases and the buildpack is out of sync?

**Comment by mataspetrikas** [comment]
I had to manually update the depenencies, after that it was running ok. Here's my PR if you would like to try it:
https://github.com/jontewks/puppeteer-heroku-buildpack/pull/20

**Comment by jontewks** [comment]
Hey @mataspetrikas, thanks a lot for opening this issue.

The linked info in the PR looks like they are trying to get the right dependencies for chromium on docker, and so there are a lot of other ones we wont need like python2.7. Would you be able to check if this list of dependencies works for you and update your PR if so:

https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch

```
gconf-service
libasound2
libatk1.0-0
libatk-bridge2.0-0
libc6
libcairo2
libcups2
libdbus-1-3
libexpat1
libfontconfig1
libgcc1
libgconf-2-4
libgdk-pixbuf2.0-0
libglib2.0-0
libgtk-3-0
libnspr4
libpango-1.0-0
libpangocairo-1.0-0
libstdc++6
libx11-6
libx11-xcb1
libxcb1
libxcomposite1
libxcursor1
libxdamage1
libxext6
libxfixes3
libxi6
libxrandr2
libxrender1
libxss1
libxtst6
ca-certificates
fonts-liberation
libappindicator1
libnss3
lsb-release
xdg-utils
wget
```

**Comment by jontewks** [comment]
I noticed this list and the buildpack's list have diverged a bit, so if that fixes your issue I'd love to accept your PR

**Comment by jontewks** [comment]
Hey @mataspetrikas, I was hoping to wait for your changes so you could merge your PR, but if the buildpack was failing I really didn't want to wait around too long and cause many other people problems, so I updated the dependencies list with what Google says is needed for Puppeteer. Maybe you could try again with the most recent version of the buildpack and let me know if its fixed? If not we can continue from there and find out whats going on with your instance.

**Comment by mataspetrikas** [comment]
@jontewks apologies for a slow response, I just tested the deploy with current build pack version - it worked! Thank you for review and fixes!

**Comment by jontewks** [comment]
@mataspetrikas no problem at all, and thank you very much for bringing it to my attention! Glad it is working for you now, let me know if there is anything else I can do.

**Comment by disaacson** [comment]
We have been having issues as well and I just tried again after seeing the update. We are still getting a dependency issue.
```Failed to launch chrome!
    /app/node_modules/puppeteer/.local-chromium/linux-555668/chrome-linux/chrome: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
    
    
    TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
      
      
      at onClose (node_modules/puppeteer/lib/Launcher.js:255:14)
      at Interface.helper.addEventListener (node_modules/puppeteer/lib/Launcher.js:244:50)
```

**Comment by disaacson** [comment]
Here is the dependency tree from chrome to libpng16 that I see on my machine
```derrick@derrick:~/neiybor/config-management$ lddtree /opt/google/chrome/chrome | grep -A 5 -B 10 libpng
    libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2
    libXss.so.1 => /usr/lib/x86_64-linux-gnu/libXss.so.1
    libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
    libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
        libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
            libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0
                libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6
            libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16
    libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
        libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0
            libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1
    libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2
        libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
```

**Comment by jontewks** [comment]
@disaacson ah yes, I thought this was ringing a bell. Can you please try the solution at the bottom of this issue and let me know if it is resolved? https://github.com/jontewks/puppeteer-heroku-buildpack/issues/14

**Comment by disaacson** [comment]
Worked. Thanks!

**Comment by remotezygote** [comment]
Still having issues in some places, but now for `libpixman-1.so.0`... which is listed in the above dependency tree, but is not installed by the buildpack... According to the heroku docs, that package is a build-only package.

**Comment by jontewks** [comment]
@remotezygote interesting. Have you tried clearing the app cache as well with the following instructions: https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

That has resolved issues for many people with old dependencies still around.

I have a test application with the newest version of this buildpack and the newest puppeteer and after clearing my cache and committing to it to cause a rebuild, its working perfectly.

Could you please clear the app cache, commit so that it forces a rebuild (restarting dynos won't do this), verify you've got the latest version of puppeteer, and verify you are using the latest version of this buildpack? After all that if you are still running into issues would you please open a new issue on here with your heroku log output, package.json contents, and maybe a screenshot of the buildpacks on your heroku app?

We will figure it out one way or another!
