### ISSUE TITLE
error: --allow-downgrades is not understood

### ISSUE THREAD

**Issue by gsar** [jontewks/puppeteer-heroku-buildpack#36]
On cedar-16 stack, I see the following error with recent versions of this buildpack:

```
-----> Puppeteer app detected
-----> Updating apt caches
       Hit http://apt.postgresql.org trusty-pgdg InRelease
       Hit http://apt.postgresql.org trusty-pgdg/main amd64 Packages
       Ign http://archive.ubuntu.com trusty InRelease
       Get:1 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
       Get:2 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
       Hit http://archive.ubuntu.com trusty Release.gpg
       Get:3 http://archive.ubuntu.com trusty-security/main amd64 Packages [979 kB]
       Get:4 http://archive.ubuntu.com trusty-security/universe amd64 Packages [348 kB]
       Get:5 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1,400 kB]
       Get:6 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [644 kB]
       Hit http://archive.ubuntu.com trusty Release
       Hit http://archive.ubuntu.com trusty/main amd64 Packages
       Hit http://archive.ubuntu.com trusty/universe amd64 Packages
       Fetched 3,503 kB in 3s (936 kB/s)
       Reading package lists...
-----> Fetching .debs for gconf-service
E: Command line option --allow-downgrades is not understood
-----> Fetching .debs for libasound2
E: Command line option --allow-downgrades is not understood
-----> Fetching .debs for libatk1.0-0
E: Command line option --allow-downgrades is not understood
-----> Fetching .debs for libatk-bridge2.0-0
E: Command line option --allow-downgrades is not understood
-----> Fetching .debs for libc6
E: Command line option --allow-downgrades is not understood
```

The resulting installation fails to run the chrome binary:

```
/app/node_modules/puppeteer/.local-chromium/linux-599821/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

at onClose (/app/node_modules/puppeteer/lib/Launcher.js:342:14) 
at Interface.helper.addEventListener (/app/node_modules/puppeteer/lib/Launcher.js:331:50) 
at Interface.emit (events.js:187:15) 
at Interface.close (readline.js:414:8) 
at Socket.onend (readline.js:167:10) 
at Socket.emit (events.js:187:15) 
at endReadableNT (_stream_readable.js:1098:12) 
at process.internalTickCallback (internal/process/next_tick.js:72:19) 
```

**Comment by gsar** [comment]
@jontewks thanks for those changes. The two extra libs that were added don't seem to be available on cedar-14.  I see this during the deploy:

```
remote: -----> Fetching .debs for libpng16-16
remote:        Reading package lists...
remote:        Building dependency tree...
remote: E: Unable to locate package libpng16-16
remote: -----> Fetching .debs for libgnutls30
remote:        Reading package lists...
remote:        Building dependency tree...
remote: E: Unable to locate package libgnutls30
```

**Comment by jontewks** [comment]
What the junk. I tested with an app on cedar 14, maybe I missed these. But that should have happened in every app? I'll give it another run through after the holiday, but at least its working for you1
