### ISSUE TITLE
Heroku Puppeter error with chrome headless - Update kernel?

### ISSUE THREAD

**Issue by fabianmedina09** [jontewks/puppeteer-heroku-buildpack#43]
28 Feb 2019 05:03:17.234168 <190>1 2019-02-28T10:03:16.613348+00:00 app web.1 - - (node:4) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
Heroku/Syslog drain
28 Feb 2019 05:03:17.235447 <190>1 2019-02-28T10:03:16.613385+00:00 app web.1 - - [0228/100316.174495:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Heroku/Syslog drain

I'm using the correct args :
const args =  ['--no-sandbox', '--disable-setuid-sandbox']

**Comment by jontewks** [comment]
Hey @fabianmedina09 thanks for bringing this up. Are you able to post the code you are trying to run as well as your package.json? 

Are you running puppeteer in headless mode?

Have you tried clearing out the cache as well? https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

**Comment by fabianmedina09** [comment]
> Hey @fabianmedina09 thanks for bringing this up. Are you able to post the code you are trying to run as well as your package.json?
> 
> Are you running puppeteer in headless mode?
> 
> Have you tried clearing out the cache as well? https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

**Comment by fabianmedina09** [comment]
> Hey @fabianmedina09 thanks for bringing this up. Are you able to post the code you are trying to run as well as your package.json?
> 
> Are you running puppeteer in headless mode?
> 
> Have you tried clearing out the cache as well? https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

I just cleaned the cache and the same error still appears. This is my code:
```
const args = proxyAddress && [`--proxy-server=${proxyAddress}`, '--no-sandbox', '--disable-setuid-sandbox']
  args && logger.info('scrapedin', `using proxy address: ${proxyAddress}`)
  const browser = await puppeteer.launch({ headless: isHeadless, args})
```
isHeadless is true allways

My package.json

`{
  "name": "fmedinacv",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "start": "nodemon app.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "engines": {
    "node": "8.11.2"
  },
  "keywords": [],
  "author": "Fabián Medina",
  "license": "MIT",
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.16.4",
    "morgan": "^1.9.1",
    "puppeteer": "^1.9.2",
    "scrapedin": "^1.0.1",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "nodemon": "^1.18.10"
  }
}`

And heroku packages:

- heroku/nodejs
- https://github.com/jontewks/puppeteer-heroku-buildpack

Full output log is:

2019-03-01T04:46:46.834599+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
2019-03-01T04:46:46.834649+00:00 app[web.1]: [0301/044646.315954:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
2019-03-01T04:46:46.834652+00:00 app[web.1]: #0 0x55b2a425e8cf base::debug::StackTrace::StackTrace()
2019-03-01T04:46:46.834654+00:00 app[web.1]: #1 0x55b2a41d472e logging::LogMessage::~LogMessage()
2019-03-01T04:46:46.834656+00:00 app[web.1]: #2 0x55b2a57110be service_manager::ZygoteHostImpl::Init()
2019-03-01T04:46:46.834658+00:00 app[web.1]: #3 0x55b2a3e3329a content::ContentMainRunnerImpl::Initialize()
2019-03-01T04:46:46.834660+00:00 app[web.1]: #4 0x55b2a3e6530a service_manager::Main()
2019-03-01T04:46:46.834662+00:00 app[web.1]: #5 0x55b2a3e31861 content::ContentMain()
2019-03-01T04:46:46.834664+00:00 app[web.1]: #6 0x55b2a83f06a8 headless::(anonymous namespace)::RunContentMain()
2019-03-01T04:46:46.834666+00:00 app[web.1]: #7 0x55b2a83f0735 headless::HeadlessBrowserMain()
2019-03-01T04:46:46.834668+00:00 app[web.1]: #8 0x55b2a3e63d74 headless::HeadlessShellMain()
2019-03-01T04:46:46.834670+00:00 app[web.1]: #9 0x55b2a1e5a1ac ChromeMain
2019-03-01T04:46:46.834672+00:00 app[web.1]: #10 0x7ffabb311b97 __libc_start_main
2019-03-01T04:46:46.834674+00:00 app[web.1]: #11 0x55b2a1e5a02a _start
2019-03-01T04:46:46.834676+00:00 app[web.1]:
2019-03-01T04:46:46.834678+00:00 app[web.1]: Received signal 6
2019-03-01T04:46:46.834680+00:00 app[web.1]: #0 0x55b2a425e8cf base::debug::StackTrace::StackTrace()
2019-03-01T04:46:46.834681+00:00 app[web.1]: #1 0x55b2a425e441 base::debug::(anonymous namespace)::StackDumpSignalHandler()
2019-03-01T04:46:46.834683+00:00 app[web.1]: #2 0x7ffac1588890 <unknown>
2019-03-01T04:46:46.834685+00:00 app[web.1]: #3 0x7ffabb32ee97 gsignal
2019-03-01T04:46:46.834687+00:00 app[web.1]: #4 0x7ffabb330801 abort
2019-03-01T04:46:46.834689+00:00 app[web.1]: #5 0x55b2a425d285 base::debug::BreakDebugger()
2019-03-01T04:46:46.834691+00:00 app[web.1]: #6 0x55b2a41d4971 logging::LogMessage::~LogMessage()
2019-03-01T04:46:46.834692+00:00 app[web.1]: #7 0x55b2a57110be service_manager::ZygoteHostImpl::Init()
2019-03-01T04:46:46.834694+00:00 app[web.1]: #8 0x55b2a3e3329a content::ContentMainRunnerImpl::Initialize()
2019-03-01T04:46:46.834696+00:00 app[web.1]: #9 0x55b2a3e6530a service_manager::Main()
2019-03-01T04:46:46.834698+00:00 app[web.1]: #10 0x55b2a3e31861 content::ContentMain()
2019-03-01T04:46:46.834700+00:00 app[web.1]: #11 0x55b2a83f06a8 headless::(anonymous namespace)::RunContentMain()
2019-03-01T04:46:46.834702+00:00 app[web.1]: #12 0x55b2a83f0735 headless::HeadlessBrowserMain()
2019-03-01T04:46:46.834703+00:00 app[web.1]: #13 0x55b2a3e63d74 headless::HeadlessShellMain()
2019-03-01T04:46:46.834705+00:00 app[web.1]: #14 0x55b2a1e5a1ac ChromeMain
2019-03-01T04:46:46.834707+00:00 app[web.1]: #15 0x7ffabb311b97 __libc_start_main
2019-03-01T04:46:46.834709+00:00 app[web.1]: #16 0x55b2a1e5a02a _start
2019-03-01T04:46:46.834711+00:00 app[web.1]: r8: 0000000000000000  r9: 00007fffcc6d2020 r10: 0000000000000008 r11: 0000000000000246
2019-03-01T04:46:46.834713+00:00 app[web.1]: r12: 00007fffcc6d22c8 r13: 0000000000000161 r14: 00007fffcc6d2c30 r15: 00007fffcc6d2c28
2019-03-01T04:46:46.834714+00:00 app[web.1]: di: 0000000000000002  si: 00007fffcc6d2020  bp: 00007fffcc6d2270  bx: 00002ab65fa39800
2019-03-01T04:46:46.834716+00:00 app[web.1]: dx: 0000000000000000  ax: 0000000000000000  cx: 00007ffabb32ee97  sp: 00007fffcc6d2020
2019-03-01T04:46:46.834718+00:00 app[web.1]: ip: 00007ffabb32ee97 efl: 0000000000000246 cgf: 0000000000000033 erf: 0000000000000000
2019-03-01T04:46:46.834720+00:00 app[web.1]: trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
2019-03-01T04:46:46.834722+00:00 app[web.1]: [end of stack trace]
2019-03-01T04:46:46.834723+00:00 app[web.1]: Calling _exit(1). Core file will not be generated.
2019-03-01T04:46:46.834725+00:00 app[web.1]:
2019-03-01T04:46:46.834727+00:00 app[web.1]:
2019-03-01T04:46:46.834729+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
2019-03-01T04:46:46.834730+00:00 app[web.1]:
2019-03-01T04:46:46.834732+00:00 app[web.1]: at onClose (/app/node_modules/puppeteer/lib/Launcher.js:360:14)
2019-03-01T04:46:46.834734+00:00 app[web.1]: at Interface.helper.addEventListener (/app/node_modules/puppeteer/lib/Launcher.js:349:50)
2019-03-01T04:46:46.834737+00:00 app[web.1]: at emitNone (events.js:111:20)
2019-03-01T04:46:46.834738+00:00 app[web.1]: at Interface.emit (events.js:208:7)
2019-03-01T04:46:46.834740+00:00 app[web.1]: at Interface.close (readline.js:368:8)
2019-03-01T04:46:46.834742+00:00 app[web.1]: at Socket.onend (readline.js:147:10)
2019-03-01T04:46:46.834744+00:00 app[web.1]: at emitNone (events.js:111:20)
2019-03-01T04:46:46.834746+00:00 app[web.1]: at Socket.emit (events.js:208:7)
2019-03-01T04:46:46.834748+00:00 app[web.1]: at endReadableNT (_stream_readable.js:1064:12)
2019-03-01T04:46:46.834749+00:00 app[web.1]: at _combinedTickCallback (internal/process/next_tick.js:138:11)
2019-03-01T04:46:46.834927+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2019-03-01T04:46:46.835028+00:00 app[web.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I am following the suggested instructions well, maybe it is a problem with the heroku dyno?

**Comment by jontewks** [comment]
It looks like sometimes args will be false. I'd try hard coding the args that are needed and removing the isHeadless since if headless is ever set to false on heroku its going to break anyways. This will at least reduce any variables to be sure we are working on the right problems and its not something silly like that.

Also I'd `npm i puppeteer@latest` to get the latest version and try with that.

Let me know how those go.

**Comment by fabianmedina09** [comment]
> It looks like sometimes args will be false. I'd try hard coding the args that are needed and removing the isHeadless since if headless is ever set to false on heroku its going to break anyways. This will at least reduce any variables to be sure we are working on the right problems and its not something silly like that.
> 
> Also I'd `npm i puppeteer@latest` to get the latest version and try with that.
> 
> Let me know how those go.

I can solve that with last version of "puppeteer": "^1.12.2"; and correcting the arguments with the identifier:

`const browser = await puppeteer.launch({ headless: isHeadless, args})` **--Before**
`const browser = await puppeteer.launch({ headless: true, args:['--no-sandbox', '--disable-setuid-sandbox'] })` **-- After**

thank you,
