### ISSUE TITLE
Error: Evaluation failed: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))     at puppeteer_evaluation_script:4:25

### ISSUE THREAD

**Issue by causztic** [jontewks/puppeteer-heroku-buildpack#52]
Hi!

I am encountering this issue on heroku-18.

```
Error: Evaluation failed: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at puppeteer_evaluation_script:4:25
```

The code works fine on localhost. Any ideas?

**Comment by jontewks** [comment]
Is this during deploy? Or after deploy and puppeteer is running? Any other output or indication puppeteer is running before this? Also can you post your package.json and the relevant code that is being run if possible?

**Comment by causztic** [comment]
Hello,

Thanks for looking into this.

1) This is after deploy and puppeteer is running.
2) I am using this particular code:

```js
    const args = ['--no-sandbox', '--disable-setuid-sandbox'];
    const browser = await puppeteer.launch({ args });
    const page = await browser.newPage();
    await page.goto(`https://www.instagram.com/${this.username}`);

    try {
      const graphEdges = await page.evaluate((postCount) => {
        const postArray = [];
        const [profile] = window._sharedData.entry_data.ProfilePage;
        const edges = profile.graphql.user.edge_owner_to_timeline_media.edges;
        edges.slice(0, postCount).forEach((edge) => {
          postArray.push(edge.node);
        });
        return postArray;
      }, count);

      const graphs = Grapher.deconstruct(graphEdges);

      await page.close();
      return graphs.reduce((accumulator, graph) =>
        accumulator.then(results =>
          this.getPostsFrom(graph).then((updatedGraph) => {
            results.push(updatedGraph);
            return results;
          })), Promise.resolve([]));
    } catch (e) {
      console.error(e);
      return null;
    }
```

Full Stack Trace is:
```
2019-09-10T15:04:20.238770+00:00 app[worker.1]: Error: Evaluation failed: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
2019-09-10T15:04:20.238794+00:00 app[worker.1]: at __puppeteer_evaluation_script__:4:27
2019-09-10T15:04:20.238796+00:00 app[worker.1]: at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
2019-09-10T15:04:20.238799+00:00 app[worker.1]: at <anonymous>
2019-09-10T15:04:20.238835+00:00 app[worker.1]: at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2019-09-10T15:04:20.239779+00:00 app[worker.1]: -- ASYNC --
2019-09-10T15:04:20.239783+00:00 app[worker.1]: at ExecutionContext.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:15)
2019-09-10T15:04:20.239785+00:00 app[worker.1]: at DOMWorld.evaluate (/app/node_modules/puppeteer/lib/DOMWorld.js:112:20)
2019-09-10T15:04:20.239788+00:00 app[worker.1]: at <anonymous>
2019-09-10T15:04:20.239948+00:00 app[worker.1]: at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2019-09-10T15:04:20.239952+00:00 app[worker.1]: -- ASYNC --
2019-09-10T15:04:20.239954+00:00 app[worker.1]: at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:15)
2019-09-10T15:04:20.239956+00:00 app[worker.1]: at Page.evaluate (/app/node_modules/puppeteer/lib/Page.js:827:43)
2019-09-10T15:04:20.239959+00:00 app[worker.1]: at Page.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:112:23)
2019-09-10T15:04:20.239962+00:00 app[worker.1]: at NightStalker.getPosts (/app/node_modules/night-stalker/dist/components/NightStalker.js:178:37)
2019-09-10T15:04:20.239965+00:00 app[worker.1]: at <anonymous>
2019-09-10T15:04:20.239967+00:00 app[worker.1]: at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

As mentioned, this works on localhost.

Here is the package.json for this library:
```json
{
  "engines": {
    "node": ">=8.10.0"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "dotenv": "^8.0.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-plugin-import": "^2.17.3",
    "eslint-plugin-jest": "^22.6.4",
    "jest": "^24.8.0"
  },
  "main": "./dist/index.js",
  "dependencies": {
    "node-persist": "^3.0.4",
    "puppeteer": "^1.14.0"
  },
  "keywords": ["instagram", "scraping", "scrape", "puppeteer"],
  "scripts": {
    "test": "jest src/tests --runInBand",
    "build": "babel src --out-dir dist",
    "prepare": "npm run build"
  }
}
```

**Comment by jontewks** [comment]
Thanks for the extra info. I haven't seen this particular error before, mainly because this buildpack is to get Puppeteer running on Heroku only and doesn't have anything to do with it after its running.

I can't say for sure why its working locally but not on heroku other than different data showing up in the page locally vs herokuly. The error says it can't iterate over something, and the only iteration I see in the code is `edges.slice(0, postCount).forEach`. Perhaps store the result of the slice in a variable and log it before calling `forEach` so you can verify its what you expect? Beyond that I don't have any other ideas other than needing to go through the standard debugging process. Sometimes it can be helpful to take screenshots of what Puppeteer is seeing as well and verifying its what you expect.

Hope you figure it out! Feel free to ask any other questions here, but I'm going to close it as it isn't an issue with the buildpack per se.

**Comment by causztic** [comment]
Thank you for looking through regardless!
