### ISSUE TITLE
Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by ghulamabbas258** [jontewks/puppeteer-heroku-buildpack#57]
2019-12-06T16:09:57.053282+00:00 app[web.1]: Error: Failed to launch chrome!
2019-12-06T16:09:57.053298+00:00 app[web.1]: 
2019-12-06T16:09:57.053301+00:00 app[web.1]: (chrome:44): Gtk-WARNING **: 16:09:57.031: cannot open display: 
2019-12-06T16:09:57.053303+00:00 app[web.1]: 
2019-12-06T16:09:57.053305+00:00 app[web.1]: 
2019-12-06T16:09:57.053308+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
2019-12-06T16:09:57.053310+00:00 app[web.1]: 
2019-12-06T16:09:57.053312+00:00 app[web.1]:     at onClose (/app/node_modules/puppeteer/lib/Launcher.js:348:14)
2019-12-06T16:09:57.053314+00:00 app[web.1]:     at ChildProcess.<anonymous> (/app/node_modules/puppeteer/lib/Launcher.js:338:60)
2019-12-06T16:09:57.053317+00:00 app[web.1]:     at ChildProcess.emit (events.js:215:7)
2019-12-06T16:09:57.053319+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
2019-12-06T16:10:26.921203+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/product/new?search=https%3A%2F%2Fwww.walmart.com%2Fip%2FHamilton-Beach-Set-n-Forget-6-Quart-Slow-Cooker-Model-33969%2F16913518" host=arcane-wave-04024.herokuapp.com request_id=34a979c5-a553-4ba2-b233-af91b577d74a fwd="124.29.252.211" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https

I got this error. I have already setup following:
puppeteer.launch({ args: ['--no-sandbox'] });

Added:  https://github.com/jontewks/puppeteer-heroku-buildpack
to Buildpacks.

Can any one help me out in this. Code was working fine on local host. But when I deploy it on heroku, it gives this error constantly.

**Comment by jontewks** [comment]
@ghulamabbas258 would you mind posting your full code if possible as well as the full error message? Also the contents of your package.json could be helpful.

Do you have `headless: false` in your puppeteer launch options too? I see a warning about chrome unable to open a display which would definitely break heroku.

Also this seems to fix random issues people have run into so its always worth a shot: https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

**Comment by ghulamabbas258** [comment]
Yes, `headless : false`. Is this causing any error?

**Comment by ghulamabbas258** [comment]
package.json


{
  "name": "Walmart Scrapper",
  "version": "1.0.0",
  "description": "Webscrapper App",
  "main": "app.js",
  "scripts": {
    "start": "node app.js"
  },
  "keywords": [
    "walmart"
  ],
  "author": "Ghulam Abbas",
  "license": "ISC",
  "dependencies": {
    "async": "^3.1.0",
    "body-parser": "^1.19.0",
    "puppeteer": "^1.20.0",
    "cheerio": "^1.0.0-rc.3",
    "connect-flash": "^0.1.1",
    "cookie-parser": "^1.4.4",
    "crypto": "^1.0.1",
    "ejs": "^2.7.1",
    "express": "^4.17.1",
    "express-promise-router": "^3.0.3",
    "express-session": "^1.17.0",
    "mongoose": "^5.7.12",
    "multer": "^1.4.2",
    "nodemailer": "^6.3.1",
    "passport": "^0.4.0",
    "passport-local": "^1.0.0",
    "passport-local-mongoose": "^5.0.1",
    "path": "^0.12.7",
    "request": "^2.88.0"
  }
}

**Comment by jontewks** [comment]
Yes `headless: false` breaks heroku as it doesn't have a GUI to show you anything. Remove that from your launch options and you should be good to go.
