### ISSUE TITLE
Failing on Heroku-18 w/ new Puppeteer v3

### ISSUE THREAD

**Issue by codebykenny** [jontewks/puppeteer-heroku-buildpack#63]
**\*\* Downgrading to puppeteer v2 is a workaround if you're experiencing this error \*\***

This buildpack needs to be updated to work with the new Puppeteer v3.

```
 /app/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
     at onClose (/app/node_modules/puppeteer/lib/Launcher.js:615:20)
     at Interface.<anonymous> (/app/node_modules/puppeteer/lib/Launcher.js:605:56)
     at Interface.emit (events.js:323:22)
     at Interface.close (readline.js:409:8)
     at Socket.onend (readline.js:187:10)
     at Socket.emit (events.js:323:22)
     at endReadableNT (_stream_readable.js:1204:12)
     at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by arifali123** [comment]
This is true I tried deploying an app like 10 times and kept wondering why this wasnt working but i just tried to downgrade my puppeteer version and it worked

**Comment by jontewks** [comment]
Thanks for letting me know!

Updated in release 1.1.7 of this buildpack. If you have your heroku pointing directly to this github repo it should work right away. I published the update on heroku as well but I'm not sure how long it takes them to pull the changes and put it on their s3 storage. Either way it should be updated already or very soon.
