### ISSUE TITLE
It seems that buildpack doesn't support browser.wsEndpoint()

### ISSUE THREAD

**Issue by iwazowsky** [jontewks/puppeteer-heroku-buildpack#66]
I am getting error when trying to connect to endpoint generated by `wsEndpoint()` function, any ideas to fix this problem?
P.S It works very fine on local
```
Error: Exactly one of browserWSEndpoint, browserURL or transport must be passed to puppeteer.connect

2020-06-07T18:23:01.370595+00:00 app[web.1]:     at Object.assert (/app/node_modules/puppeteer/lib/helper.js:51:15)

2020-06-07T18:23:01.370596+00:00 app[web.1]:     at ChromeLauncher.connect (/app/node_modules/puppeteer/lib/Launcher.js:158:18)

2020-06-07T18:23:01.370597+00:00 app[web.1]:     at Puppeteer.connect (/app/node_modules/puppeteer/lib/Puppeteer.js:63:31)

2020-06-07T18:23:01.370598+00:00 app[web.1]:     at scrap (/app/__sapper__/build/server/server.js:109:37)

2020-06-07T18:23:01.370599+00:00 app[web.1]:     at get$1 (/app/__sapper__/build/server/server.js:242:24)

2020-06-07T18:23:01.370599+00:00 app[web.1]:     at handle_route (/app/__sapper__/build/server/server.js:1995:11)

2020-06-07T18:23:01.370600+00:00 app[web.1]:     at Array.find_route (/app/__sapper__/build/server/server.js:2009:5)

2020-06-07T18:23:01.370600+00:00 app[web.1]:     at nth_handler (/app/__sapper__/build/server/server.js:4491:14)

2020-06-07T18:23:01.370600+00:00 app[web.1]:     at /app/__sapper__/build/server/server.js:4491:31

2020-06-07T18:23:01.370601+00:00 app[web.1]:     at Array.<anonymous> (/app/__sapper__/build/server/server.js:4541:4)

2020-06-07T18:23:01.370601+00:00 app[web.1]:     at nth_handler (/app/__sapper__/build/server/server.js:4491:14)

2020-06-07T18:23:01.370602+00:00 app[web.1]:     at /app/__sapper__/build/server/server.js:4491:31

2020-06-07T18:23:01.370622+00:00 app[web.1]:     at Array.<anonymous> (/app/__sapper__/build/server/server.js:4541:4)

2020-06-07T18:23:01.370622+00:00 app[web.1]:     at nth_handler (/app/__sapper__/build/server/server.js:4491:14)

2020-06-07T18:23:01.370623+00:00 app[web.1]:     at /app/__sapper__/build/server/server.js:4491:31

2020-06-07T18:23:01.370623+00:00 app[web.1]:     at Array.<anonymous> (/app/__sapper__/build/server/server.js:4459:4)
```

**Comment by jontewks** [comment]
Hey @iwazowsky, this buildpack's only goal is to get puppeteer running on Heroku. Once its running I don't think it has any effect on puppeteer's actions. 

My only guesses are to make sure you are running puppeteer as headless since heroku has no UI to show you puppeteer, and to be sure the no sandbox flag is passed as well. Mind posting your code so we can see whats going on?
