### ISSUE TITLE
Error with saving screenshots

### ISSUE THREAD

**Issue by oihamza** [jontewks/puppeteer-heroku-buildpack#68]
Thanks for creating this awesome buildpack! 

I'm having so many issues with using Puppeteer + Heroku and I'm on the verge of just giving up... I've been experiencing a bunch of issues with saving screenshots from Puppeteer in Heroku. I've combed through all the issues here and can't seem to find anything related, so I'm not sure if it's related to this buildpack or Puppeteer and Heroku in general.

Basically, I'm trying to take a screenshot so I can Tweet it, and have created a bot that will Tweet regularly.

The screenshot works perfectly on my machine, and each time I run my script it overwrites the existing image path. However, when I deploy to Heroku, the image doesn't seem to load at all. I've tried formatting my script a number of ways (will post below), but none of they things seem to work. The bot still Tweets a random phrase as normal, but it's always the same image each time which leads me to believe Puppeteer isn't running properly. 

Here are the different scripts that I've tried:

`const puppeteer = require('puppeteer')

const takeScreenshot = async() => {
  const browser = await puppeteer.launch(
    {args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
    ],
  });
  const page = await browser.newPage();
  await page.setViewport({
      width: 720,
      height: 720,
      deviceScaleFactor: 1,
  });
  await page.goto('https://google.com');
  await page.screenshot({path: 'option/folder/screenshot.png'});
  await browser.close();
}

takeScreenshot();
`

`const puppeteer = require('puppeteer')
const options = {path: 'option/folder/screenshot.png',}
const takeScreenshot = (async() => {
	const browser = await puppeteer.launch({
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
    ]
	});
	try {
		const page = await browser.newPage();
		console.log("here")
		await page.setViewport({
			width: 720,
			height: 720,
			deviceScaleFactor: 1,
		});
		await page.goto('https://google.com');
		console.log("on this site")
		await page.screenshot(options)
    console.log("saved image")
	} catch (err) {
		console.error(err, err.message);
	} finally {
    await browser.close();
	}
});

takeScreenshot();
`

My heroku buildpacks are in the following order: 
<img width="420" alt="Screen Shot 2020-09-15 at 11 57 42 PM" src="https://user-images.githubusercontent.com/58232877/93290700-4a883780-f7af-11ea-8423-b32f576c41a3.png">

Do you know how I can make sure my Puppeteer screenshots save? Any help is appreciated! 😄

**Comment by oihamza** [comment]
I should also add that I don't see any errors in Heroku. Everything looks totally normal when I run a dyno...

**Comment by jontewks** [comment]
Hey @oihamza,

This buildpack is just to get puppeteer running on heroku, but doesn't have any effect on how it works after its running, so I don't believe this buildpack is responsible for issues saving screenshots.

One thought that did occur to me though, is that heroku may have different file permissions regarding overwriting existing files than your local computer does. Have you tried running it on heroku but not overwriting the previous screenshot each time, and instead giving each new screenshot a unique name? That probably wouldn't be ideal for the long run as you'll load up on storage space, but that would at least tell you if that was the problem or not.

Good luck!

**Comment by joshmcarthur** [comment]
We have experienced a very similar problem with our Rails application that uses Puppeteer to generate PDFs from HTML files. The files would be saved as zero bytes, and the version of Chrome packaged with puppeteer crashed with the following message:

```
Connecting to web.1 on ⬢ nzsl...
Input path: file:///app/tmp/pdf_rendering/1600368639-20b6d81ec0aefed49e26-input.html
Output path: /app/tmp/eoin2.pdf
(node:4626) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/app/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4626) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4626) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

https://github.com/ODNZSL/nzsl-online/issues/1149 has a log of what we tried, but in short:

* Clearing the repo cache
* Removing and re-adding the build pack
* Dyno restarts

We also observed on the dyno that the shared libraries that puppeteer was missing were in fact present (presumably, added by this buildpack):

```
▶ heroku run bash -a nzsl            
Running bash on ⬢ nzsl... up, run.1783 (Standard-1X)
~ $ find . -name "libnss3.so"
./.apt/usr/lib/x86_64-linux-gnu/libnss3.so
```

We also observed that LD_LIBRARY_PATH and LIBRARY_PATH appeared to be set correctly to resolve the shared libraries:

```
LIBRARY_PATH=/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib/i386-linux-gnu:/app/.apt/usr/lib:
LD_LIBRARY_PATH=/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib/i386-linux-gnu:/app/.apt/usr/lib:
```

Chrome also reports that it has all the libraries it needs:

```
~/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux $ ldd chrome
	linux-vdso.so.1 (0x00007ffd85b23000)
	/app/vendor/jemalloc/lib/libjemalloc.so (0x00007f43396e7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f43394e3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f43392c4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f43390bc000)
	libgobject-2.0.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f4338e68000)
	libglib-2.0.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f4338b51000)
	libnss3.so => /app/.apt/usr/lib/x86_64-linux-gnu/libnss3.so (0x00007f433880d000)
	libnssutil3.so => /app/.apt/usr/lib/x86_64-linux-gnu/libnssutil3.so (0x00007f43385de000)
	libsmime3.so => /app/.apt/usr/lib/x86_64-linux-gnu/libsmime3.so (0x00007f43383b2000)
	libnspr4.so => /app/.apt/usr/lib/x86_64-linux-gnu/libnspr4.so (0x00007f4338175000)
	libatk-1.0.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f4337f4f000)
	libatk-bridge-2.0.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007f4337d1e000)
	libX11.so.6 => /app/.apt/usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f43379e6000)
	libX11-xcb.so.1 => /app/.apt/usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f43377e4000)
	libxcb.so.1 => /app/.apt/usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f43375bc000)
	libxcb-dri3.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f43373b8000)
	libXcomposite.so.1 => /app/.apt/usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f43371b5000)
	libXdamage.so.1 => /app/.apt/usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f4336fb2000)
	libXext.so.6 => /app/.apt/usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f4336da0000)
	libXfixes.so.3 => /app/.apt/usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f4336b9a000)
	libcups.so.2 => /app/.apt/usr/lib/x86_64-linux-gnu/libcups.so.2 (0x00007f433690e000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f43366c1000)
	libgio-2.0.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f4336322000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f43360f0000)
	libdrm.so.2 => /app/.apt/usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f4335edf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4335b41000)
	libXrandr.so.2 => /app/.apt/usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f4335936000)
	libgbm.so.1 => /app/.apt/usr/lib/x86_64-linux-gnu/libgbm.so.1 (0x00007f4335727000)
	libasound.so.2 => /app/.apt/usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f4335420000)
	libpangocairo-1.0.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f4335213000)
	libpango-1.0.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f4334fc6000)
	libcairo.so.2 => /app/.apt/usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f4334ca9000)
	libatspi.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libatspi.so.0 (0x00007f4334a79000)
	libgtk-3.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007f4334171000)
	libgdk-3.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libgdk-3.so.0 (0x00007f4333e7b000)
	libgdk_pixbuf-2.0.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f4333c57000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4333a3f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f433364e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f43449b2000)
	libstdc++.so.6 => /app/.apt/usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f43332c5000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f43330bd000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f4332e4b000)
	libplc4.so => /app/.apt/usr/lib/x86_64-linux-gnu/libplc4.so (0x00007f4332c46000)
	libplds4.so => /app/.apt/usr/lib/x86_64-linux-gnu/libplds4.so (0x00007f4332a42000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f433283e000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f4332638000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f43323ed000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f4332087000)
	libavahi-common.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-common.so.3 (0x00007f4331e7b000)
	libavahi-client.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-client.so.3 (0x00007f4331c6a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4331a4d000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f43317c9000)
	libgmodule-2.0.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f43315c5000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f433139d000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f4331182000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f4330f2e000)
	libXrender.so.1 => /app/.apt/usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f4330d24000)
	libwayland-server.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007f4330b11000)
	libfontconfig.so.1 => /app/.apt/usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f43308cc000)
	libpangoft2-1.0.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f43306b6000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f4330402000)
	libthai.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f43301f9000)
	libpixman-1.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f432ff54000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f432fd22000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f432fb1f000)
	libxcb-render.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f432f912000)
	libXi.so.6 => /app/.apt/usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f432f702000)
	libcairo-gobject.so.2 => /app/.apt/usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007f432f4f9000)
	libepoxy.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libepoxy.so.0 (0x00007f432f1f8000)
	libXinerama.so.1 => /app/.apt/usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f432eff5000)
	libXcursor.so.1 => /app/.apt/usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f432edeb000)
	libxkbcommon.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f432ebac000)
	libwayland-cursor.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007f432e9a4000)
	libwayland-egl.so.1 => /app/.apt/usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007f432e7a2000)
	libwayland-client.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f432e593000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f432e37e000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f432e0a8000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f432de76000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f432dc72000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f432da67000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f432d738000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f432d51b000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f432d19d000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f432cf8a000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f432cd54000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f432cb20000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f432c89f000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f432c679000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f432c45d000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f432c141000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f432bef4000)
	libharfbuzz.so.0 => /app/.apt/usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f432bc56000)
	libdatrie.so.1 => /app/.apt/usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f432ba4f000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f432b84b000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f432b636000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f432b42f000)
	libgraphite2.so.3 => /app/.apt/usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f432b202000)
```

We 'fixed' this issue by downgrading Puppeteer to a 2.0 release. While we still need to investigate why this happens, my suspicion is that Puppeteer may launch Chrome in such a way that `LD_LIBRARY_PATH` or `LIBRARY_PATH`  do not resolve correctly, causing libraries to be missing. Because I this happens only on Heroku, not locally, I wonder if it has something to do with the .so files being located in .apt/ rather than /usr/lib.
