### ISSUE TITLE
Error: Failed to launch the browser process! on a Heroku~like PaaS

### ISSUE THREAD

**Issue by 7hibault** [jontewks/puppeteer-heroku-buildpack#70]
Hi, and thanks for the buildpack!

I hope it's not inappropriate for me to create this issue, as my issue is not directly related to Heroku. I have forked this repo to make it compatible with Scalingo, a PaaS provider that works in a very similar fashion to Heroku.

The deployment works fine using that buildpack and their node buildpack, however it crashes when trying to launch a headless chrome using

```javascript
const browser = await puppeteer.launch({ args:  ['--no-sandbox', '--disable-setuid-sandbox'] });
```

I get this error

```
Error: Failed to launch the browser process!
[0924/183844.745281:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0924/183844.772930:ERROR:platform_thread_posix.cc(129)] pthread_create: Resource temporarily unavailable (11)
[0924/183844.796928:ERROR:platform_thread_posix.cc(129)] pthread_create: Resource temporarily unavailable (11)
[0924/183844.772960:FATAL:media_stream_manager.cc(743)] Check failed: video_capture_thread_->Start(). 
#0 0x559e00337239 base::debug::CollectStackTrace()
#1 0x559e002b30f3 base::debug::StackTrace::StackTrace()
#2 0x559e002c3d70 logging::LogMessage::~LogMessage()
#3 0x559e002c465e logging::LogMessage::~LogMessage()
#4 0x559dfe835494 content::MediaStreamManager::MediaStreamManager()
#5 0x559dfe835183 content::MediaStreamManager::MediaStreamManager()
#6 0x559dfe5469d1 content::BrowserMainLoop::BrowserThreadsStarted()
#7 0x559dfe961943 content::StartupTaskRunner::RunAllTasksNow()
#8 0x559dfe545fe5 content::BrowserMainLoop::CreateStartupTasks()
#9 0x559dfe5490f7 content::BrowserMainRunnerImpl::Initialize()
#10 0x559e04c14b6c headless::HeadlessContentMainDelegate::RunProcess()
#11 0x559dffe73e11 content::ContentMainRunnerImpl::RunServiceManager()
#12 0x559dffe738de content::ContentMainRunnerImpl::Run()
#13 0x559dffed4689 service_manager::Main()
#14 0x559dffe71a61 content::ContentMain()
#15 0x559dffed38cd headless::(anonymous namespace)::RunContentMain()
#16 0x559dffed35cc headless::HeadlessShellMain()
#17 0x559dfd7a7427 ChromeMain
#18 0x7f1f5b536b97 __libc_start_main
#19 0x559dfd7a726a _start

Received signal 6
#0 0x559e00337239 base::debug::CollectStackTrace()
#1 0x559e002b30f3 base::debug::StackTrace::StackTrace()
#2 0x559e00336dd5 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f1f61bcb890 (/lib/x86_64-linux-gnu/libpthread-2.27.so+0x1288f)
#4 0x7f1f5b553e97 gsignal
#5 0x7f1f5b555801 abort
#6 0x559e00335d35 base::debug::BreakDebugger()
#7 0x559e002c4210 logging::LogMessage::~LogMessage()
#8 0x559e002c465e logging::LogMessage::~LogMessage()
#9 0x559dfe835494 content::MediaStreamManager::MediaStreamManager()
#10 0x559dfe835183 content::MediaStreamManager::MediaStreamManager()
#11 0x559dfe5469d1 content::BrowserMainLoop::BrowserThreadsStarted()
#12 0x559dfe961943 content::StartupTaskRunner::RunAllTasksNow()
#13 0x559dfe545fe5 content::BrowserMainLoop::CreateStartupTasks()
#14 0x559dfe5490f7 content::BrowserMainRunnerImpl::Initialize()
#15 0x559e04c14b6c headless::HeadlessContentMainDelegate::RunProcess()
#16 0x559dffe73e11 content::ContentMainRunnerImpl::RunServiceManager()
#17 0x559dffe738de content::ContentMainRunnerImpl::Run()
#18 0x559dffed4689 service_manager::Main()
#19 0x559dffe71a61 content::ContentMain()
#20 0x559dffed38cd headless::(anonymous namespace)::RunContentMain()
#21 0x559dffed35cc headless::HeadlessShellMain()
#22 0x559dfd7a7427 ChromeMain
#23 0x7f1f5b536b97 __libc_start_main
#24 0x559dfd7a726a _start
  r8: 0000000000000000  r9: 00007fff47404d40 r10: 0000000000000008 r11: 0000000000000246
 r12: 00003ef3d943eb40 r13: 00007fff47404fa0 r14: 00003ef3d943eb50 r15: aaaaaaaaaaaaaaaa
  di: 0000000000000002  si: 00007fff47404d40  bp: 00007fff47404f90  bx: 00007fff474057d4
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f1f5b553e97  sp: 00007fff47404d40
  ip: 00007f1f5b553e97 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:327:22)
    at Interface.EventEmitter.emit (domain.js:483:12)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Maybe you've encountered a similar issue before?

If that's of any use, I've also tried using an APT buildpack to install directly all the dependencies.

Environment:

- puppeteer: 5.3.1
- stack: [scalingo-18](https://hub.docker.com/r/scalingo/scalingo-18)
- buildpacks: [slightly modified puppeteer-heroku-buildpack](https://github.com/7hibault/puppeteer-scalingo-buildpack) to allow scalingo-18 stack & [nodejs-buildpack](https://github.com/Scalingo/nodejs-buildpack)

**Comment by jontewks** [comment]
Hey @7hibault. I have never run into this sort of issue before. The buildpack installs required dependencies, so if the error was a missing library, that would be easy to resolve. But this error is about connecting to a bus and socket, which is more OS level interactions rather than dependencies for puppeteer. I'm guessing thats the difference between scalingo and local/heroku, but having never used scalingo its hard for me to say. Perhaps a good place to start is to see if they have any official chromium buildpack, which is what I started with from heroku to get the puppeteer one up and running.

**Comment by North-West-Wind** [comment]
Ah crap I also encounter this one

**Comment by figoaranta** [comment]
I think ur error can be solved by adding await browser.close(); at the end of ur scrape function.

**Comment by asafstr2** [comment]
same here
