### ISSUE TITLE
Unable to open X display

### ISSUE THREAD

**Issue by phcs93** [jontewks/puppeteer-heroku-buildpack#81]
When running puppeteer in headful mode on heroku, I get the following error:

```
2021-02-16T05:35:58.836742+00:00 app[worker.1]: Error: Failed to launch the browser process!
2021-02-16T05:35:58.836743+00:00 app[worker.1]: [20:20:0216/053558.511826:ERROR:browser_main_loop.cc(1468)] Unable to open X display.       
2021-02-16T05:35:58.836743+00:00 app[worker.1]: Received signal 11 SEGV_MAPERR 000000000000
2021-02-16T05:35:58.836744+00:00 app[worker.1]: #0 0x55a57ef70399 base::debug::CollectStackTrace()
2021-02-16T05:35:58.836744+00:00 app[worker.1]: #1 0x55a57eed12a3 base::debug::StackTrace::StackTrace()
2021-02-16T05:35:58.836745+00:00 app[worker.1]: #2 0x55a57ef6ff35 base::debug::(anonymous namespace)::StackDumpSignalHandler()
2021-02-16T05:35:58.836745+00:00 app[worker.1]: #3 0x7fcfd99b93c0 (/usr/lib/x86_64-linux-gnu/libpthread-2.31.so+0x153bf)
2021-02-16T05:35:58.836747+00:00 app[worker.1]: #4 0x55a581966f38 ChromeBrowserMainExtraPartsViewsLinux::~ChromeBrowserMainExtraPartsViewsLinux()
2021-02-16T05:35:58.836748+00:00 app[worker.1]: #5 0x55a57eb18140 ChromeBrowserMainParts::~ChromeBrowserMainParts()
2021-02-16T05:35:58.836748+00:00 app[worker.1]: #6 0x55a57eb17cfe ChromeBrowserMainPartsLinux::~ChromeBrowserMainPartsLinux()
2021-02-16T05:35:58.836748+00:00 app[worker.1]: #7 0x55a57d2111bf content::BrowserMainLoop::~BrowserMainLoop()
2021-02-16T05:35:58.836748+00:00 app[worker.1]: #8 0x55a57d2112ce content::BrowserMainLoop::~BrowserMainLoop()
2021-02-16T05:35:58.836749+00:00 app[worker.1]: #9 0x55a57d215c2b content::BrowserMainRunnerImpl::Shutdown()
2021-02-16T05:35:58.836749+00:00 app[worker.1]: #10 0x55a57d215738 content::BrowserMainRunnerImpl::~BrowserMainRunnerImpl()
2021-02-16T05:35:58.836750+00:00 app[worker.1]: #11 0x55a57d210d30 content::BrowserMain()
2021-02-16T05:35:58.836750+00:00 app[worker.1]: #12 0x55a57ea9b796 content::ContentMainRunnerImpl::RunServiceManager()
2021-02-16T05:35:58.836750+00:00 app[worker.1]: #13 0x55a57ea9b3c7 content::ContentMainRunnerImpl::Run()
2021-02-16T05:35:58.836750+00:00 app[worker.1]: #14 0x55a57eafcad1 service_manager::Main()
2021-02-16T05:35:58.836751+00:00 app[worker.1]: #15 0x55a57ea99631 content::ContentMain()
2021-02-16T05:35:58.836751+00:00 app[worker.1]: #16 0x55a57c4ef5ae ChromeMain
2021-02-16T05:35:58.836751+00:00 app[worker.1]: #17 0x7fcfd7ded0b3 __libc_start_main
2021-02-16T05:35:58.836752+00:00 app[worker.1]: #18 0x55a57c4ef3ea _start
2021-02-16T05:35:58.836752+00:00 app[worker.1]: r8: 0000000000000000  r9: 0000000000000001 r10: 0000000000000002 r11: 000008cffcab58e8      
2021-02-16T05:35:58.836752+00:00 app[worker.1]: r12: aaaaaaaaaaaaaaaa r13: 000008cffca3f330 r14: 000008cffca6b5d8 r15: 000008cffc9b0460     
2021-02-16T05:35:58.836752+00:00 app[worker.1]: di: 000008cffca6b5a0  si: 000008cffca13b20  bp: 00007ffee6a9ac90  bx: 000008cffca6b5a0      
2021-02-16T05:35:58.836753+00:00 app[worker.1]: dx: 000008cffca13b20  ax: 0000000000000000  cx: fffffffd52d41d70  sp: 00007ffee6a9ac80      
2021-02-16T05:35:58.836753+00:00 app[worker.1]: ip: 000055a581966f38 efl: 0000000000010206 cgf: 0000000000000033 erf: 0000000000000004      
2021-02-16T05:35:58.836753+00:00 app[worker.1]: trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
2021-02-16T05:35:58.836753+00:00 app[worker.1]: [end of stack trace]
2021-02-16T05:35:58.836753+00:00 app[worker.1]: Calling _exit(1). Core file will not be generated.
2021-02-16T05:35:58.836754+00:00 app[worker.1]:
2021-02-16T05:35:58.836754+00:00 app[worker.1]: 
2021-02-16T05:35:58.836754+00:00 app[worker.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md 
2021-02-16T05:35:58.836754+00:00 app[worker.1]:
2021-02-16T05:35:58.836754+00:00 app[worker.1]: at onClose (/app/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
2021-02-16T05:35:58.836755+00:00 app[worker.1]: at ChildProcess.<anonymous> (/app/node_modules/puppeteer/lib/launcher/BrowserRunner.js:150:76)
2021-02-16T05:35:58.836755+00:00 app[worker.1]: at ChildProcess.emit (events.js:327:22)
2021-02-16T05:35:58.836755+00:00 app[worker.1]: at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
````

Here is my `launch` call:

```
const browser = await puppeteer.launch({
    headless: false,
    args: [
        '--no-sandbox', 
        '--disable-setuid-sandbox', 
        '--mute-audio'
    ]
});
```

Buildpack is installed:

![image](https://user-images.githubusercontent.com/7042908/108024413-4b91ef00-7003-11eb-8c0e-b804894998cc.png)

**Comment by jontewks** [comment]
Hey @phcs93,

You aren't able to run Heroku with `headless: false`. Heroku doesn't have a GUI so when you run `headless: false` Puppeteer will try to open a browser window to show you the output which will cause a failure on Heroku. Just remove that line since the default is `headless: true`.

**Comment by vortice3D** [comment]
Hi there @jontewks:

I don't know if a new issue would be the best solution for these cases, but I have exactly this same problem, Heroku crashes when Puppeteer is used in "headful" mode, that I need because I'm rendering webgl scenes.

Any help with a cloud service similar to Heroku that we can use.

Best reagards.

**Comment by jontewks** [comment]
Hey @vortice3D, I don't know specifically as I've never run into the need but I did see this pop up, might be possible on google cloud compute. https://medium.com/google-cloud/graphical-user-interface-gui-for-google-compute-engine-instance-78fccda09e5c

**Comment by vortice3D** [comment]
Thank you very much for the link.

Best regards.
